<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModulesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Generate some dummy data
        $modules = [
            [
                'codeModule' => 'EGTS202',
                'libelleModule' => 'Français',
                'ordreModule' => 1,
                'MasseHoraireTotal' => 115.00,
                'MHT' => 115.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTS203',
                'libelleModule' => 'Anglais technique',
                'ordreModule' => 2,
                'MasseHoraireTotal' => 50.00,
                'MHT' => 50.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTS204',
                'libelleModule' => 'Culture entrepreneuriale',
                'ordreModule' => 3,
                'MasseHoraireTotal' => 45.00,
                'MHT' => 45.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTS205',
                'libelleModule' => 'Compétences comportementales',
                'ordreModule' => 4,
                'MasseHoraireTotal' => 30.00,
                'MHT' => 30.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTS208',
                'libelleModule' => 'Entrepreneuriat-PIE 2',
                'ordreModule' => 5,
                'MasseHoraireTotal' => 80.00,
                'MHT' => 80.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTSA206',
                'libelleModule' => 'Culture et techniques avancées du numérique',
                'ordreModule' => 6,
                'MasseHoraireTotal' => 30.00,
                'MHT' => 30.00,
                'Coef' => 1,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M201',
                'libelleModule' => 'Préparation d’un projet web',
                'ordreModule' => 7,
                'MasseHoraireTotal' => 60.00,
                'MHT' => 60.00,
                'Coef' => 1,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M202',
                'libelleModule' => 'Approche agile',
                'ordreModule' => 8,
                'MasseHoraireTotal' => 120.00,
                'MHT' => 120.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M203',
                'libelleModule' => 'Gestion des données',
                'ordreModule' => 9,
                'MasseHoraireTotal' => 90.00,
                'MHT' => 90.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M204',
                'libelleModule' => 'Développement front-end',
                'ordreModule' => 10,
                'MasseHoraireTotal' => 90.00,
                'MHT' => 90.00,
                'Coef' => 3,
                'EFM_Regional' => 'O',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M205',
                'libelleModule' => 'Développement back-end',
                'ordreModule' => 11,
                'MasseHoraireTotal' => 120.00,
                'MHT' => 120.00,
                'Coef' => 3,
                'EFM_Regional' => 'O',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M206',
                'libelleModule' => 'Création d’une application Cloud native',
                'ordreModule' => 12,
                'MasseHoraireTotal' => 90.00,
                'MHT' => 90.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M207',
                'libelleModule' => 'Projet de synthèse',
                'ordreModule' => 13,
                'MasseHoraireTotal' => 60.00,
                'MHT' => 60.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M208',
                'libelleModule' => 'Intégration du milieu professionnel',
                'ordreModule' => 14,
                'MasseHoraireTotal' => 160.00,
                'MHT' => 160.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'DWFS',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTS202',
                'libelleModule' => 'Français',
                'MasseHoraireTotal' => 115.00,
                'MHT' => 115.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTS203',
                'libelleModule' => 'Anglais technique',
                'MasseHoraireTotal' => 50.00,
                'MHT' => 50.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTS204',
                'libelleModule' => 'Culture entrepreneuriale',
                'MasseHoraireTotal' => 45.00,
                'MHT' => 45.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTS205',
                'libelleModule' => 'Compétences comportementales',
                'MasseHoraireTotal' => 30.00,
                'MHT' => 30.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTS208',
                'libelleModule' => 'Entrepreneuriat-PIE 2',
                'MasseHoraireTotal' => 80.00,
                'MHT' => 80.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'EGTSA206',
                'libelleModule' => 'Culture et techniques avancées du numérique',
                'MasseHoraireTotal' => 30.00,
                'MHT' => 30.00,
                'Coef' => 1,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M201',
                'libelleModule' => 'Bureautique',
                'MasseHoraireTotal' => 50.00,
                'MHT' => 50.00,
                'Coef' => 1,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M202',
                'libelleModule' => 'Droit du travail',
                'MasseHoraireTotal' => 40.00,
                'MHT' => 40.00,
                'Coef' => 1,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M203',
                'libelleModule' => 'Droit commercial',
                'MasseHoraireTotal' => 50.00,
                'MHT' => 50.00,
                'Coef' => 1,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M204',
                'libelleModule' => 'Marketing digital',
                'MasseHoraireTotal' => 60.00,
                'MHT' => 60.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M205',
                'libelleModule' => 'Techniques de vente et de négociation',
                'MasseHoraireTotal' => 80.00,
                'MHT' => 80.00,
                'Coef' => 3,
                'EFM_Regional' => 'O',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M206',
                'libelleModule' => 'E-commerce',
                'MasseHoraireTotal' => 40.00,
                'MHT' => 40.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M207',
                'libelleModule' => 'Management de la force de vente',
                'MasseHoraireTotal' => 80.00,
                'MHT' => 80.00,
                'Coef' => 3,
                'EFM_Regional' => 'O',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M208',
                'libelleModule' => 'Gestion des approvisionnements',
                'MasseHoraireTotal' => 60.00,
                'MHT' => 60.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M209',
                'libelleModule' => 'Trade marketing',
                'MasseHoraireTotal' => 80.00,
                'MHT' => 80.00,
                'Coef' => 2,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M210',
                'libelleModule' => 'Logiciel Sphinx',
                'MasseHoraireTotal' => 30.00,
                'MHT' => 30.00,
                'Coef' => 1,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M211',
                'libelleModule' => 'Marketing international',
                'MasseHoraireTotal' => 90.00,
                'MHT' => 90.00,
                'Coef' => 3,
                'EFM_Regional' => 'O',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ],
            [
                'codeModule' => 'M212',
                'libelleModule' => 'Merchandising',
                'MasseHoraireTotal' => 60.00,
                'MHT' => 60.00,
                'Coef' => 3,
                'EFM_Regional' => 'N',
                'filiereModule' => 'GECM',
                'semestreModule' => 'S1',
            ]

        ];

        // Insert data into the modules table
        DB::table('modules')->insert($modules);
    }
}
